In [11]:
%load_ext autoreload
%autoreload 2

import ipywidgets as widgets
from camera import CameraReader, display_frame
from funciones import eliminar_ruido, transmisor, receptor
from scipy import fftpack
import matplotlib.pyplot as plt
from scipy.signal import medfilt
import numpy as np
from collections import Counter
import heapq


cam = CameraReader()
vid_height, vid_width = cam.get_resolution()
print("Resolución del video: {0}x{1}p".format(vid_width, vid_height))
print("Cuadros por segundo: {0}".format(cam.get_fps()))

out = widgets.Image(layout=widgets.Layout(width=str(vid_width), 
                                          height=str(vid_height)))
display(out)

# Probamos cada fase con el 1er frame del video
frame1 = next(cam)

#for frame in cam:
    
    # Implemente esta función en proyecto.py
frame_limpio = eliminar_ruido(frame1)
    
    # Implemente esta función en proyecto.py
frame_comprimido = transmisor(frame_limpio)
    
    # Mida el peso en bits de frame_comprimido
    
    # Implemente esta función en proyecto.py
frame = receptor(frame_comprimido)
    
#display_frame(out, frame.astype('uint8'))
    
"""
        fig, ax = plt.subplots(1, 1, figsize=(15, 10), tight_layout=True);
        # Espectro
        freq_x = fftpack.fftshift(fftpack.fftfreq(n=frame.shape[1]))
        freq_y = fftpack.fftshift(fftpack.fftfreq(n=frame.shape[0]))
        ax.imshow(np.log(1+np.abs(fftpack.fftshift(fftpack.fft2(frame_sucio))))[200:-200, 200:-200], cmap=plt.cm.Spectral_r,
                 extent=(freq_x[800], freq_x[-800], freq_y[50], freq_y[-50]))        # Reconstrucción
        fig, ax2 = plt.subplots(1, 1, figsize=(15, 10), tight_layout=True);
        ax2.imshow(np.log(1+np.abs(fftpack.fftshift(fftpack.fft2(frame))))[200:-200, 200:-200], cmap=plt.cm.Spectral_r,
                   extent=(freq_x[800], freq_x[-800], freq_y[50], freq_y[-50])) 
        fig, ax3 = plt.subplots(1, 1, figsize=(15, 10), tight_layout=True);
        ax3.matshow(frame[:,:], cmap=plt.cm.Greys_r)
        break
    
""" 
      
   

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Iniciando lector de camara
OpenCV version: major: 4, minor: 2, subminor: 0
Resolución del video: 848x480p
Cuadros por segundo: 29.97002997002997


Image(value=b'', layout="Layout(height='480', width='848')")

Antes de cuantizar:  [[1206.35341979 -110.39370541  -73.47486625 ...    4.0315275
     4.92876593   -6.51157544]
 [  23.85550548  -53.64969422  -37.9984426  ...   -3.27144522
     6.35058978   -4.77715599]
 [ -13.05792534  -40.2533504   -33.1878434  ...   -7.28519183
    10.53304727   -6.81680869]
 ...
 [  -3.86243524   -7.75788526  -12.39359081 ...    7.61233286
    -6.39277018    3.89741255]
 [   3.42878154    5.94993648    7.74903389 ...   -7.68383611
     5.7811374    -3.60915298]
 [  -5.39756038   -6.23246594   -7.61294998 ...    4.74585385
    -3.00147232    1.40192606]]
Después de cuantizar:  [[402. -55. -37. ...   1.   0.  -1.]
 [ 12. -27. -13. ...  -0.   1.  -0.]
 [ -4. -20. -11. ...  -1.   1.  -1.]
 ...
 [ -1.  -1.  -1. ...   0.  -0.   0.]
 [  0.   0.   1. ...  -0.   0.  -0.]
 [ -0.  -0.  -0. ...   0.  -0.   0.]]


'\n        fig, ax = plt.subplots(1, 1, figsize=(15, 10), tight_layout=True);\n        # Espectro\n        freq_x = fftpack.fftshift(fftpack.fftfreq(n=frame.shape[1]))\n        freq_y = fftpack.fftshift(fftpack.fftfreq(n=frame.shape[0]))\n        ax.imshow(np.log(1+np.abs(fftpack.fftshift(fftpack.fft2(frame_sucio))))[200:-200, 200:-200], cmap=plt.cm.Spectral_r,\n                 extent=(freq_x[800], freq_x[-800], freq_y[50], freq_y[-50]))        # Reconstrucción\n        fig, ax2 = plt.subplots(1, 1, figsize=(15, 10), tight_layout=True);\n        ax2.imshow(np.log(1+np.abs(fftpack.fftshift(fftpack.fft2(frame))))[200:-200, 200:-200], cmap=plt.cm.Spectral_r,\n                   extent=(freq_x[800], freq_x[-800], freq_y[50], freq_y[-50])) \n        fig, ax3 = plt.subplots(1, 1, figsize=(15, 10), tight_layout=True);\n        ax3.matshow(frame[:,:], cmap=plt.cm.Greys_r)\n        break\n    \n'